import React from "react";

const About = () => {
    
    return (
        <div>
        <h1>About</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod elit ut sagittis porta. Duis sapien purus, imperdiet ac consectetur eu, varius non mi. Phasellus fringilla risus eu cursus molestie. Suspendisse potenti. Suspendisse commodo posuere diam non fringilla. Vivamus feugiat hendrerit sapien. Phasellus vehicula non velit vitae aliquet. Aenean at luctus ante, ac laoreet ligula. Fusce nec sem non neque elementum aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel lorem lobortis, interdum felis volutpat, ultricies diam. Fusce pellentesque tempor lacinia. Suspendisse vehicula, mi eget pharetra volutpat, augue ante mollis tellus, sed semper mauris eros eget elit. Mauris vitae aliquet enim. In augue dolor, pretium non iaculis ut, lacinia non sapien. Mauris vel eros nec odio accumsan iaculis vehicula eget ligula. Donec ex turpis, imperdiet at sapien a, mollis sollicitudin mi. Nam dolor enim, lacinia a condimentum non, bibendum at risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam gravida interdum consequat. In tempus odio quis tortor aliquam, eget cursus dolor volutpat. Sed viverra at enim nec porttitor. Nulla faucibus vel velit vitae aliquet. Nunc eget elementum nunc, eu facilisis eros.</p>
        
        <p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam elit, aliquet at maximus interdum, vehicula scelerisque arcu. Nunc nec ligula nisi. Ut tempus elementum dui sit amet varius. Nulla consectetur urna ac pellentesque elementum. Nullam sed scelerisque ligula. Nunc pharetra enim sed tellus condimentum feugiat. Aenean hendrerit ipsum in diam elementum, in feugiat ex laoreet. Ut efficitur molestie magna et dictum. Vestibulum euismod commodo urna nec facilisis. Nullam porta hendrerit placerat. Curabitur pulvinar congue tempor.</i></p>
    </div>
    )
}

export default About;